---
# tasks file for journald
- name:     Replace configuration file
  template:
    src:    journald.conf.j2
    dest:   /etc/systemd/journald.conf
  notify:
    - journald restart
  tags:
    - journald

- name:     Install systemd-journal-gateway
  yum:
    name:   systemd-journal-gateway
    state:  latest
  tags:
    - journald
